"""Direct port of STYLE_PRESETS and the human-aware tuning table from
script.js. Kept as plain dicts, not classes — mirrors the JS object literals
exactly so the two can be diffed against each other by eye.

If script.js's STYLE_PRESETS or applyHumanPresetSliders table ever change,
this file needs the same edit made here too — there is no single shared
source of truth between the browser and native versions.
"""

STYLE_PRESETS = {
    "ultimate": {
        "label": "Ultimate Studio",
        "engine": "ultimate",
        "background": (250, 246, 238),
        "ink": (22, 28, 36),
        "low_threshold": 32,
        "high_threshold": 108,
        "bilateral_diameter": 7,
        "sigma": 48,
        "smooth_passes": 1,
        "xdog_sigma": 0.82,
        "xdog_tau": 0.983,
        "xdog_phi": 210,
        "clean_speckles": True,
        "merge_double_edge": False,
    },
    "manga": {
        "label": "Manga Contrast",
        "engine": "ultimate",
        "background": (255, 255, 255),
        "ink": (8, 8, 10),
        "low_threshold": 34,
        "high_threshold": 118,
        "bilateral_diameter": 9,
        "sigma": 72,
        "smooth_passes": 1,
        "xdog_sigma": 0.88,
        "xdog_tau": 0.988,
        "xdog_phi": 280,
        "clean_speckles": True,
        "merge_double_edge": True,
    },
    "studio": {
        "label": "Studio Ink",
        "engine": "ultimate",
        "background": (248, 244, 234),
        "ink": (28, 32, 38),
        "low_threshold": 38,
        "high_threshold": 118,
        "bilateral_diameter": 7,
        "sigma": 52,
        "smooth_passes": 1,
        "xdog_sigma": 0.7,
        "xdog_tau": 0.987,
        "xdog_phi": 240,
        "clean_speckles": True,
        "merge_double_edge": False,
    },
    "neon": {
        "label": "Neon Pop",
        "engine": "ultimate",
        "background": (10, 8, 22),
        "ink": (0, 230, 200),
        "low_threshold": 22,
        "high_threshold": 80,
        "bilateral_diameter": 9,
        "sigma": 68,
        "smooth_passes": 1,
        "xdog_sigma": 0.74,
        "xdog_tau": 0.98,
        "xdog_phi": 210,
        "clean_speckles": True,
        "merge_double_edge": False,
    },
    "warm": {
        "label": "Warm Sketch",
        "engine": "ultimate",
        "background": (255, 247, 232),
        "ink": (92, 44, 18),
        "low_threshold": 32,
        "high_threshold": 104,
        "bilateral_diameter": 7,
        "sigma": 58,
        "smooth_passes": 1,
        "xdog_sigma": 0.92,
        "xdog_tau": 0.976,
        "xdog_phi": 160,
        "clean_speckles": True,
        "merge_double_edge": False,
    },
    "vivid": {
        "label": "Vivid Toon",
        "engine": "ultimate",
        "background": (255, 255, 255),
        "ink": (28, 28, 168),
        "low_threshold": 18,
        "high_threshold": 66,
        "bilateral_diameter": 11,
        "sigma": 96,
        "smooth_passes": 1,
        "xdog_sigma": 0.76,
        "xdog_tau": 0.983,
        "xdog_phi": 210,
        "clean_speckles": True,
        "merge_double_edge": False,
    },
    "blueprint": {
        "label": "Blueprint Draft",
        "engine": "ultimate",
        "background": (224, 236, 244),
        "ink": (16, 52, 88),
        "low_threshold": 48,
        "high_threshold": 144,
        "bilateral_diameter": 5,
        "sigma": 44,
        "smooth_passes": 1,
        "xdog_sigma": 0.68,
        "xdog_tau": 0.99,
        "xdog_phi": 210,
        "clean_speckles": True,
        "merge_double_edge": False,
    },
    "classic": {
        "label": "Classic Canny",
        "engine": "classic",
        "background": (255, 255, 255),
        "ink": (0, 0, 0),
        "low_threshold": 40,
        "high_threshold": 100,
        "bilateral_diameter": 13,
        "sigma": 90,
        "smooth_passes": 2,
        "clean_speckles": True,
        "merge_double_edge": True,
    },
    "human": {
        "label": "Portrait",
        "engine": "ultimate",
        "background": (250, 246, 238),
        "ink": (22, 28, 36),
        "low_threshold": 28,
        "high_threshold": 100,
        "bilateral_diameter": 7,
        "sigma": 44,
        "smooth_passes": 1,
        "xdog_sigma": 0.72,
        "xdog_tau": 0.986,
        "xdog_phi": 210,
        "clean_speckles": True,
        "merge_double_edge": False,
    },
    "subject": {
        "label": "Subject only",
        "engine": "ultimate",
        "background": (255, 255, 255),
        "ink": (18, 18, 20),
        "low_threshold": 30,
        "high_threshold": 110,
        "bilateral_diameter": 7,
        "sigma": 48,
        "smooth_passes": 1,
        "xdog_sigma": 0.8,
        "xdog_tau": 0.985,
        "xdog_phi": 220,
        "clean_speckles": True,
        "merge_double_edge": False,
    },
    "pencil": {
        "label": "Soft pencil",
        "engine": "ultimate",
        "background": (250, 246, 238),
        "ink": (54, 42, 32),
        "low_threshold": 24,
        "high_threshold": 90,
        "bilateral_diameter": 7,
        "sigma": 52,
        "smooth_passes": 1,
        "xdog_sigma": 1.05,
        "xdog_tau": 0.945,
        "xdog_phi": 70,
        "clean_speckles": False,
        "merge_double_edge": False,
    },
    "custom": {
        "label": "Custom / Experiment",
        "engine": "classic",
        "background": (255, 255, 255),
        "ink": (0, 0, 0),
        "low_threshold": 60,
        "high_threshold": 180,
        "bilateral_diameter": 13,
        "sigma": 90,
        "smooth_passes": 2,
    },
}

# From applyHumanPresetSliders (script.js). A preset with no entry here falls
# back to "ultimate", same as the JS `table[presetKey] || table.ultimate`.
HUMAN_TUNING = {
    "human": {"skin_smooth": 0.84, "hair_boost": 1.45, "silhouette_boost": 0.95, "subject_isolation": 0.28},
    "subject": {"skin_smooth": 0.7, "hair_boost": 1.32, "silhouette_boost": 1.0, "subject_isolation": 0.94},
    "manga": {"skin_smooth": 0.8, "hair_boost": 1.4, "silhouette_boost": 0.9, "subject_isolation": 0.22},
    "neon": {"skin_smooth": 0.55, "hair_boost": 1.32, "silhouette_boost": 0.88, "subject_isolation": 0.55},
    "blueprint": {"skin_smooth": 0.76, "hair_boost": 1.32, "silhouette_boost": 0.72, "subject_isolation": 0.18},
    "classic": {"skin_smooth": 0.8, "hair_boost": 1.32, "silhouette_boost": 0.72, "subject_isolation": 0.38},
    "ultimate": {"skin_smooth": 0.8, "hair_boost": 1.32, "silhouette_boost": 0.72, "subject_isolation": 0.38},
    "studio": {"skin_smooth": 0.78, "hair_boost": 1.32, "silhouette_boost": 0.82, "subject_isolation": 0.38},
    # Gentler throughout to match pencil's already-soft line (xdog_phi 70 vs.
    # ultimate's 210) — see the matching comment in script.js.
    "pencil": {"skin_smooth": 0.72, "hair_boost": 1.2, "silhouette_boost": 0.6, "subject_isolation": 0.26},
}


def get_preset(name):
    if name not in STYLE_PRESETS:
        raise ValueError(f"Unknown preset '{name}'. Choices: {', '.join(STYLE_PRESETS)}")
    return STYLE_PRESETS[name]


def get_human_tuning(name):
    return HUMAN_TUNING.get(name, HUMAN_TUNING["ultimate"])
